[build]
  base = "fplnepal-dashboard"  # ✅ Ensures the build runs inside fplnepal-dashboard
  command = "npm install && npm run build"
  publish = "build"


[dev]
  command = "npm --prefix fplnepal-dashboard run start"  # Run start script in frontend directory
  targetPort = 3000                                      # Default React port

[functions]
  directory = "fplnepal-dashboard/functions"
  node_bundler = "esbuild"
