[build]
  base = "fplnepal-dashboard"
  command = "npm install && npm run build"
  publish = "build"

[dev]
  command = "npm --prefix fplnepal-dashboard run start"
  targetPort = 3000

[functions]
  directory = "backend/functions"
  node_bundler = "esbuild"